# Generated by Django 5.2.6 on 2025-09-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payer_payment_payer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('chapa', 'Chapa')], default='paystack', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('ngn', 'NGN'), ('usd', 'USD'), ('eur', 'EUR'), ('gbp', 'GBP'), ('aud', 'AUD'), ('cad', 'CAD')], default='ngn', max_length=10),
        ),
    ]
