# Generated by Django 5.2.6 on 2025-09-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_cart_cartitem_unique_product_per_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_addition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
