# Generated by Django 5.2.6 on 2025-09-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_price_at_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_addition',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
