# Generated by Django 5.2.6 on 2025-09-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_price_at_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
