# Generated by Django 5.2.6 on 2025-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('warranty', models.IntegerField(blank=True, help_text="Number of years of product's warranty.Leave empty if there is none", null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('category', models.ManyToManyField(to='products.category')),
            ],
        ),
    ]
