# Generated by Django 5.2.6 on 2025-09-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(help_text='Category will be returned as a list', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (e.g. 10 = 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, help_text="Number of years of product's warranty. Leave empty if there is none", null=True),
        ),
    ]
