# Generated by Django 5.2.6 on 2025-09-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(help_text='Category will be returned as a list of category IDs', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Discount percentage (e.g. 10 = 10%)', max_digits=5),
        ),
    ]
